# ===== Compiler =====
CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -Ilib/SDL2/include

LDFLAGS = -Llib/SDL2/lib
LIBS = -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf

# ===== Directories =====
SRC_DIR = src
OBJ_DIR = obj
BIN = tiny_football.exe

# ===== Files =====
SRC = $(wildcard $(SRC_DIR)/*.cpp)
OBJ = $(patsubst $(SRC_DIR)/%.cpp, $(OBJ_DIR)/%.o, $(SRC))

# ===== Build =====
all: $(BIN)

$(BIN): $(OBJ)
	$(CXX) $(OBJ) -o $@ $(LDFLAGS) $(LIBS)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
#	 @if not exist $(OBJ_DIR) mkdir $(OBJ_DIR)
	mkdir -p $(OBJ_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
#	@if exist $(OBJ_DIR) rmdir /s /q $(OBJ_DIR)
#	@if exist $(BIN) del $(BIN)
	rm -rf $(OBJ_DIR)
	rm -f $(BIN)

run: all
#	set PATH=%CD%\lib\SDL2\bin;%PATH% && $(BIN)
	PATH="$(PWD)/lib/SDL2/bin:$$PATH" ./$(BIN)
